# Generated by Django 2.2.3 on 2019-08-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='collegeId',
            new_name='student',
        ),
    ]
