# Generated by Django 2.2.3 on 2019-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190806_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isLoggedIn',
            field=models.IntegerField(db_column='Login Status', default=0),
        ),
    ]
